[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { package = "config", path="../config"}
delphi = { package = "delphi", path="../consensus/delphi"}
acs = { package = "aacs", path="../consensus/aacs"}
dkg = { package = "ladkg", path = "../ladkg"}
consensus = { package = "consensus", path="../consensus"}
util = { package = "util", path="../util"}
anyhow = "1"
types = { package = "types", path="../types"}
clap = {version = "2", features = ["yaml"]}
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.8"
log="*"
simple_logger="*"
fnv = "1.0.3"
signal-hook = "0"

network = { package = "network", git = "https://github.com/linghe-yang/libnet-rs.git" }
async-trait = "0.1.89"
futures-util = "0.3.31"
rand = "0.8"

hashrand = { package = "hashrand", git = "https://github.com/linghe-yang/hashrand-rs.git" }
hrconfig = {package = "config" , git = "https://github.com/linghe-yang/hashrand-rs.git"}
hrcrypto = {package = "crypto" , git = "https://github.com/linghe-yang/hashrand-rs.git"}
crypto = {package = "crypto", path = "../crypto"}
avsss = { package = "avsss", git = "https://github.com/linghe-yang/lvss.git"}
env_logger = "0.8.4"